config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :chields
  resources :parents
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chield.rb
class Chield < ApplicationRecord
  has_attached_file :aadhar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :aadhar, content_type: /\Aimage\/.*\z/

  has_many :users

  # validates_presence_of :name, :b_date, :user_id
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_attached_file :aadhar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :aadhar, content_type: /\Aimage\/.*\z/

  has_many :users

  # validates_presence_of :name, :b_date, :user_id, :aadhar
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :aadhar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :aadhar, content_type: /\Aimage\/.*\z/

  belongs_to :parent
  belongs_to :chield

  # validates_presence_of :name, :b_date, :aadhar, :parent_id, :chield_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chields_controller.rb
class ChieldsController < ApplicationController
  def show
    @chield = Chield.find(params[:id])
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  def show
    @user = Parent.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order("created_at desc").page(params[:page]).per(5)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :aadhar, :b_date, :parent_id, :chield_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chields_helper.rb
module ChieldsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chield.name %>
</p>

<p>
  <strong>Aadhar:</strong>
  <img class="img-thumbnail" src="<%= @chield.aadhar %>" width="50"/>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @chield.b_date&.strftime("%d-%b-%Y") %>
</p>

<%= link_to 'Back', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hindustani</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',  integrity:'sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm', crossorigin:'anonymous' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/froala-editor@3.0.0-beta.1//js/froala_editor.pkgd.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Aadhar:</strong>
  <img class="img-thumbnail" src="<%= @user.aadhar %>" width="50"/>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @user.b_date&.strftime("%d-%b-%Y") %>
</p>

<%= link_to 'Back', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :aadhar %>
    <%= form.file_field :aadhar %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="col-sm-12">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center">Users</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Aadhar</th>
        <th>Birth date</th>
        <th>Father Name</th>
        <th>Chield</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td>
            <a href="<%= user.aadhar %>" id="aadhar_image" width="100">
              <img class="img-thumbnail" src="<%= user.aadhar %>" width="50"/>
            </a>
          </td>
          
          <td><%= user.b_date&.strftime("%d-%b-%Y") %></td>
          <td><%= link_to user.parent.name, parent_path(user.parent.id) %></td>
          <td><%= link_to user.chield.name, chield_path(user.chield.id) %></td>
          <td><%= link_to fa_icon('eye'), user, class: "fa-2x", style: 'color: green' %></td>
          <td><%= link_to fa_icon('pencil-square-o'), edit_user_path(user), class: "fa-2x", style: 'color: red' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <nav class="pagination d-flex justify-content-center">
    <%= paginate @users, :page_links => false %>
  </nav>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Aadhar:</strong>
  <img class="img-thumbnail" src="<%= @user.aadhar %>" width="50"/>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @user.b_date&.strftime("%d-%b-%Y") %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @user.parent.name %>
</p>

<p>
  <strong>Chield:</strong>
  <%= @user.chield.name %>
</p>

<%= link_to fa_icon('pencil-square-o'), edit_user_path(@user) %> |
<%= link_to fa_icon('arrow-left'), users_path %>